Repository dojot/dojot, pull requests merged in 2020-08, with the labels that each got.

#1599 Add environment variable to enable requesting certificates from client
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Config.js
  subscription-engine/kafka-ws/index.js
Labels: Team:Backend, Type:Enhancement, service:kafka-ws

#1606 [dev] Add environment variable to enable requesting certificates from client
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Config.js
  subscription-engine/kafka-ws/index.js
Labels: Team:Backend, Type:Enhancement, service:kafka-ws

#1597 [feature] Add new Kafka WS example that works with Dojot environment
  subscription-engine/kafka-ws/.eslintignore
  subscription-engine/kafka-ws/examples/README.md
  subscription-engine/kafka-ws/examples/With Dojot/README.md
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/Client.js
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/Dockerfile
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/package-lock.json
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/package.json
  subscription-engine/kafka-ws/examples/With Dojot/docker-compose.yml
  subscription-engine/kafka-ws/examples/Without Dojot/README.md
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/Client.js
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/Dockerfile
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/package-lock.json
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/package.json
  subscription-engine/kafka-ws/examples/Without Dojot/certs/client/ca-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/client/client-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/client/client-key.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/server/ca-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/server/server-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/server/server-key.pem
  subscription-engine/kafka-ws/examples/Without Dojot/docker-compose.yml
  subscription-engine/kafka-ws/examples/Without Dojot/kafkacat-producer.sh
  subscription-engine/kafka-ws/examples/Without Dojot/redis.conf
Labels: Team:Backend, Type:Feature, service:kafka-ws

#1618 [feature] [dev] Add new Kafka WS example that works with Dojot environment
  subscription-engine/kafka-ws/.eslintignore
  subscription-engine/kafka-ws/examples/README.md
  subscription-engine/kafka-ws/examples/With Dojot/README.md
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/Client.js
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/Dockerfile
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/package-lock.json
  subscription-engine/kafka-ws/examples/With Dojot/WSClient/package.json
  subscription-engine/kafka-ws/examples/With Dojot/docker-compose.yml
  subscription-engine/kafka-ws/examples/Without Dojot/README.md
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/Client.js
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/Dockerfile
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/package-lock.json
  subscription-engine/kafka-ws/examples/Without Dojot/WSClient/package.json
  subscription-engine/kafka-ws/examples/Without Dojot/certs/client/ca-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/client/client-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/client/client-key.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/server/ca-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/server/server-cert.pem
  subscription-engine/kafka-ws/examples/Without Dojot/certs/server/server-key.pem
  subscription-engine/kafka-ws/examples/Without Dojot/docker-compose.yml
  subscription-engine/kafka-ws/examples/Without Dojot/kafkacat-producer.sh
  subscription-engine/kafka-ws/examples/Without Dojot/redis.conf
Labels: Team:Backend, Type:Feature, service:kafka-ws

#1616 Improved documentation x509-identity-mnmt
  x509-identity-mgmt/README.md
Labels: Team:Backend, Team:Security, Type:Documentation

#1620 improved documentation x509-identity-mnmt (branch "development")
  x509-identity-mgmt/README.md
Labels: Team:Backend, Team:Security, Type:Documentation

#1598 Tool for generating dummy certificates
  tools/certgen/README.md
  tools/certgen/bin/certgen.sh
Labels: Type:Enhancement

#1607 Fix Locust Docker files
  connector/mqtt/locust/Docker/docker-compose-master.yml
  connector/mqtt/locust/Docker/docker-compose-slave.yml
  connector/mqtt/locust/Docker/scripts/generate_certs/Dockerfile
  connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
  connector/mqtt/locust/master_entrypoint.sh
  connector/mqtt/locust/slave_entrypoint.sh
  connector/mqtt/locust/src/config.py
Labels: Team:Backend, Type:Bug :bug:, Type:Enhancement

#1624 [release] Fix Locust Docker files
  connector/mqtt/locust/Docker/docker-compose-master.yml
  connector/mqtt/locust/Docker/docker-compose-slave.yml
  connector/mqtt/locust/Docker/scripts/generate_certs/Dockerfile
  connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
  connector/mqtt/locust/master_entrypoint.sh
  connector/mqtt/locust/slave_entrypoint.sh
  connector/mqtt/locust/src/config.py
Labels: Team:Backend, Type:Bug :bug:, Type:Enhancement

#1623 improve debug when trying send msg to kafka
  connector/mqtt/vernemq/v2k-bridge/app/AgentMessenger.js
Labels: service:V2K

#1622 doc: fix default Kafka consumption topic variable value
  connector/mqtt/vernemq/k2v-bridge/README.md
Labels: service:K2V

#1643 Bringing CertTools from "development" to "feature 0.5.0"
  tools/certgen/README.md
  tools/certgen/bin/certgen.sh
  tools/certreq/README.md
  tools/certreq/bin/certreq.sh
Labels: Type:Enhancement

#1583 [release] Add milliseconds to v2k timestamp
  connector/mqtt/vernemq/v2k-bridge/app/utils.js
  connector/mqtt/vernemq/v2k-bridge/package-lock.json
  connector/mqtt/vernemq/v2k-bridge/package.json
Labels: service:V2K

#1642 [dev] [locust] Add Locust Exporter
  connector/mqtt/locust/Docker/docker-compose-master.yml
  connector/mqtt/locust/Docker/docker-compose-slave.yml
  connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
  connector/mqtt/locust/README.md
Labels: Team:Backend, Type:Feature

#1641 [release] [locust] Add Locust Exporter
  connector/mqtt/locust/Docker/docker-compose-master.yml
  connector/mqtt/locust/Docker/docker-compose-slave.yml
  connector/mqtt/locust/Docker/scripts/generate_certs/docker-compose.yml
  connector/mqtt/locust/README.md
Labels: Team:Backend, Type:Feature

#1668 [dev] Add bool operator
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Conditions/Conditions.js
  subscription-engine/kafka-ws/app/Config.js
  subscription-engine/kafka-ws/app/Utils.js
  subscription-engine/kafka-ws/app/WhereProcessing/OperatorValidator.js
  subscription-engine/kafka-ws/app/WhereProcessing/WhereParser.js
  subscription-engine/kafka-ws/test/integration/Conditions.test.js
  subscription-engine/kafka-ws/test/unit/Utils.test.js
Labels: Team:Backend, Type:Feature, service:kafka-ws

#1665 [release] Add bool operator
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Conditions/Conditions.js
  subscription-engine/kafka-ws/app/Config.js
  subscription-engine/kafka-ws/app/Utils.js
  subscription-engine/kafka-ws/app/WhereProcessing/OperatorValidator.js
  subscription-engine/kafka-ws/app/WhereProcessing/WhereParser.js
  subscription-engine/kafka-ws/test/integration/Conditions.test.js
  subscription-engine/kafka-ws/test/unit/Utils.test.js
Labels: Team:Backend, Type:Feature, service:kafka-ws

#1654 [release v0.5.0] update x509-identity-mgmt docs
  x509-identity-mgmt/README.md
  x509-identity-mgmt/js/apidocs/api-description.apib
Labels: Type:Documentation

#1581 [release] - crl download fix
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/retrieveCRL.sh
Labels: Team:Backend, Type:Bug :bug:

#1666 [development] update x509-identity-mgmt docs
  x509-identity-mgmt/README.md
  x509-identity-mgmt/js/apidocs/api-description.apib
Labels: Type:Documentation

#1644 [Release v0.5.0] Update IoT Agent MqTT docs
  connector/mqtt/vernemq/README.md
Labels: Type:Documentation

#1667 [development] Update IoT Agent MqTT docs
  connector/mqtt/vernemq/README.md
Labels: Type:Documentation

#1663 [development] Validating inputs and sanitizing outputs
  x509-identity-mgmt/js/package-lock.json
  x509-identity-mgmt/js/src/db.js
  x509-identity-mgmt/js/src/routes/certificates-router.js
  x509-identity-mgmt/js/tests/integration/cert-get.test.js
Labels: Team:Backend, Type:Bug :bug:

#1580 [development]: crl download fix
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/retrieveCRL.sh
Labels: Team:Backend, Type:Bug :bug:
