Repository dojot/dojot, pull requests merged in 2020-06, with the labels that each got.

#1496 [mqtt/vernemq/k2v-bridge] Change to microservice SDK
  connector/mqtt/vernemq/k2v-bridge/Dockerfile
  connector/mqtt/vernemq/k2v-bridge/README.md
  connector/mqtt/vernemq/k2v-bridge/app/AgentMessenger.js
  connector/mqtt/vernemq/k2v-bridge/app/MqttClient.js
  connector/mqtt/vernemq/k2v-bridge/app/app.js
  connector/mqtt/vernemq/k2v-bridge/app/config.js
  connector/mqtt/vernemq/k2v-bridge/app/utils.js
  connector/mqtt/vernemq/k2v-bridge/app/utils/utils.js
  connector/mqtt/vernemq/k2v-bridge/bin/entryPoint.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/_initVariables.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/checkBrokerCertHasRevoke.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/checkCertificateChain.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/checkExpirationCertificate.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/createCSR.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/ejbca_client.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/generateKeyPair.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/retrieveCACertificate.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/retrieveCRL.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/saveFormattedCRT.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/signCert.sh
  connector/mqtt/vernemq/k2v-bridge/package-lock.json
  connector/mqtt/vernemq/k2v-bridge/package.json
  connector/mqtt/vernemq/k2v-bridge/test/unit/agentMessenger.test.js
  connector/mqtt/vernemq/k2v-bridge/test/unit/config.test.js
  connector/mqtt/vernemq/k2v-bridge/test/unit/mqttClient.test.js
  connector/mqtt/vernemq/k2v-bridge/test/unit/utils.test.js
Labels: Epic:100K_IoTDevices, Team:Backend, Type:Enhancement

#1514 Process hangs when broker connection is down
  connector/mqtt/vernemq/k2v-bridge/Dockerfile
  connector/mqtt/vernemq/k2v-bridge/app/AgentMessenger.js
  connector/mqtt/vernemq/k2v-bridge/app/MqttClient.js
  connector/mqtt/vernemq/k2v-bridge/app/utils.js
  connector/mqtt/vernemq/k2v-bridge/package-lock.json
  connector/mqtt/vernemq/k2v-bridge/package.json
  connector/mqtt/vernemq/k2v-bridge/test/unit/agentMessenger.test.js
  connector/mqtt/vernemq/k2v-bridge/test/unit/mqttClient.test.js
  connector/mqtt/vernemq/k2v-bridge/test/unit/utils.test.js
Labels: Epic:100K_IoTDevices, Needs:Review, Team:Backend, Type:Bug :bug:, Type:Enhancement, service:K2V

#1463 [fix] vernemq disconnect plugin bugfix
  connector/mqtt/vernemq/broker/README.md
  connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/readme.md
  connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/src/clean_sess.erl
  connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/src/dojot_disconnect_plugin.app.src
  connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/src/dojot_disconnect_plugin.erl
  connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/src/dojot_disconnect_plugin_sup.erl
  connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/src/utils.erl
Labels: Epic:100K_IoTDevices, Team:Backend, Type:Bug :bug:

#1517 Add tini to VerneMQ
  connector/mqtt/vernemq/broker/Dockerfile
Labels: Epic:100K_IoTDevices, Team:Backend, Type:Bug :bug:
