Repository dojot/dojot, pull requests merged in 2021-01, with the labels that each got.

#1924 [x509-identity-mgmt] Improved EJBCA configuration scripts
  x509-identity-mgmt/ejbca/README.md
  x509-identity-mgmt/ejbca/bin/after-deployed-pre.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/admin-creation.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/certificate-authorities-creation.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/configuration-variables.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/ejbca-commands.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/exec.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/import-profiles.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/services-creation.sh
  x509-identity-mgmt/ejbca/bin/dojot-custom/tls-certificate-generation.sh
  x509-identity-mgmt/ejbca/resources/profiles/certprofile_Internal-1805040431.xml
  x509-identity-mgmt/ejbca/resources/profiles/certprofile_InternalCA-1561197140.xml
  x509-identity-mgmt/ejbca/resources/profiles/entityprofile_Internal-1583112258.xml
  x509-identity-mgmt/examples/simple/docker-compose.yml
Labels: Type:Enhancement

#1817 [verne,k2v,v2k] Remove scripts tls to use cert-sidecar
  connector/mqtt/vernemq/broker/Dockerfile
  connector/mqtt/vernemq/broker/README.md
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/_initVariables.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkBrokerCertHasRevoke.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkCertificateChain.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/checkExpirationCertificate.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/createCSR.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/generateKeyPair.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/retrieveCACertificate.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/retrieveCRL.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/saveFormattedCRT.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/scripts_tls/signCert.sh
  connector/mqtt/vernemq/broker/bin/vmq_dojot/vmq_dojot.sh
  connector/mqtt/vernemq/k2v-bridge/Dockerfile
  connector/mqtt/vernemq/k2v-bridge/bin/entryPoint.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/_initVariables.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/checkBrokerCertHasRevoke.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/checkCertificateChain.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/checkExpirationCertificate.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/createCSR.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/ejbca_client.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/generateKeyPair.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/retrieveCACertificate.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/retrieveCRL.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/saveFormattedCRT.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/signCert.sh
  connector/mqtt/vernemq/v2k-bridge/Dockerfile
  connector/mqtt/vernemq/v2k-bridge/bin/entryPoint.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/_initVariables.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/checkBrokerCertHasRevoke.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/checkCertificateChain.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/checkExpirationCertificate.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/createCSR.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/ejbca_client.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/generateKeyPair.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/retrieveCACertificate.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/retrieveCRL.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/saveFormattedCRT.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/signCert.sh
Labels: Type:Enhancement, service:K2V, service:V2K

#1933 [v0.5.2] vernemq image build
  connector/mqtt/vernemq/broker/Dockerfile
  connector/mqtt/vernemq/broker/bin/NOTICE
  connector/mqtt/vernemq/broker/bin/build.sh
  connector/mqtt/vernemq/broker/bin/vernemq.sh
  connector/mqtt/vernemq/broker/examples/vernemq.conf
Labels: Type:Feature

#1931 [development] build new vernemq docker image
  connector/mqtt/vernemq/broker/Dockerfile
  connector/mqtt/vernemq/broker/bin/NOTICE
  connector/mqtt/vernemq/broker/bin/build.sh
  connector/mqtt/vernemq/broker/bin/vernemq.sh
  connector/mqtt/vernemq/broker/examples/vernemq.conf
Labels: Type:Feature

#1659 [v0.5.0] added metrics to locust
  connector/mqtt/locust/src/mqtt_locust/mqtt_client.py
  connector/mqtt/locust/src/utils.py
  connector/mqtt/locust/tests/mqtt_locust/test_mqtt_client.py
  connector/mqtt/locust/tests/test_utils.py
Labels: Team:Backend, Type:Feature

#1813 feat: add cert-sidecar
  .github/workflows/cert-sidecar.yml
  tools/cert-sidecar/.dockerignore
  tools/cert-sidecar/.eslintrc.json
  tools/cert-sidecar/.gitignore
  tools/cert-sidecar/.npmrc
  tools/cert-sidecar/Dockerfile
  tools/cert-sidecar/LICENSE
  tools/cert-sidecar/README.md
  tools/cert-sidecar/app/App.js
  tools/cert-sidecar/app/CronsCertsMgmt.js
  tools/cert-sidecar/app/Utils.js
  tools/cert-sidecar/app/certificatesMgmt/Certificates.js
  tools/cert-sidecar/app/certificatesMgmt/index.js
  tools/cert-sidecar/app/opensslWrapper/OpensslUtils.js
  tools/cert-sidecar/app/opensslWrapper/index.js
  tools/cert-sidecar/app/x509IdentityMgmt/Requests.js
  tools/cert-sidecar/app/x509IdentityMgmt/index.js
  tools/cert-sidecar/config/default.conf
  tools/cert-sidecar/config/development.conf
  tools/cert-sidecar/config/simple.conf
  tools/cert-sidecar/docs/diagrams/diagram.png
  tools/cert-sidecar/docs/diagrams/diagram_plant_uml
  tools/cert-sidecar/example/README.md
  tools/cert-sidecar/example/client/.dockerignore
  tools/cert-sidecar/example/client/Dockerfile
  tools/cert-sidecar/example/client/client.js
  tools/cert-sidecar/example/docker-compose.yml
  tools/cert-sidecar/example/server/.dockerignore
  tools/cert-sidecar/example/server/Dockerfile
  tools/cert-sidecar/example/server/server.js
  tools/cert-sidecar/index.js
  tools/cert-sidecar/license-exceptions.json
  tools/cert-sidecar/package-lock.json
  tools/cert-sidecar/package.json
  tools/cert-sidecar/test/integration/CertificatesMgmt.test.js
  tools/cert-sidecar/test/integration/OpensslWrapper.test.js
  tools/cert-sidecar/test/integration/X509IdentityMgmt.test.js
  tools/cert-sidecar/test/integration/crl.pem
  tools/cert-sidecar/test/unit/App.test.js
  tools/cert-sidecar/test/unit/CronsCertsMgmt.test.js
  tools/cert-sidecar/test/unit/Utils.test.js
Labels: Cert-Sidecar, Type:Feature
