Repository dojot/dojot, pull requests merged in 2021-03, with the labels that each got.

#2022 [x509-identity-mgmt] Notification of events on Kafka
  iam/x509-identity-mgmt/Dockerfile
  iam/x509-identity-mgmt/README.md
  iam/x509-identity-mgmt/js/.vscode/launch.json
  iam/x509-identity-mgmt/js/apidocs/api-description.apib
  iam/x509-identity-mgmt/js/config/default.conf
  iam/x509-identity-mgmt/js/config/development.conf
  iam/x509-identity-mgmt/js/index.js
  iam/x509-identity-mgmt/js/package-lock.json
  iam/x509-identity-mgmt/js/package.json
  iam/x509-identity-mgmt/js/schemas/defs.json
  iam/x509-identity-mgmt/js/src/DIContainer.js
  iam/x509-identity-mgmt/js/src/core/RelativeDistinguishedNames.json
  iam/x509-identity-mgmt/js/src/core/dnUtils.js
  iam/x509-identity-mgmt/js/src/core/tokenGen.js
  iam/x509-identity-mgmt/js/src/db/CertificateModel.js
  iam/x509-identity-mgmt/js/src/db/CommonModel.js
  iam/x509-identity-mgmt/js/src/db/TrustedCAModel.js
  iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrProvider.js
  iam/x509-identity-mgmt/js/src/express/interceptors/readinessInterceptor.js
  iam/x509-identity-mgmt/js/src/express/interceptors/tokenParsingInterceptor.js
  iam/x509-identity-mgmt/js/src/express/routes/certificateRoutes.js
  iam/x509-identity-mgmt/js/src/notifications/NotificationEngine.js
  iam/x509-identity-mgmt/js/src/notifications/NotificationKafkaHealthCheck.js
  iam/x509-identity-mgmt/js/src/notifications/OwnershipNotifier.js
  iam/x509-identity-mgmt/js/src/notifications/TrustedCANofitier.js
  iam/x509-identity-mgmt/js/src/services/CertificateService.js
  iam/x509-identity-mgmt/js/src/services/TrustedCAService.js
  iam/x509-identity-mgmt/js/tests/json-schema/certificates.test.js
  iam/x509-identity-mgmt/js/tests/unitary/core/tokenGen.test.js
  iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrProvider.test.js
  iam/x509-identity-mgmt/js/tests/unitary/express/interceptors/scopedDIInterceptor.test.js
  iam/x509-identity-mgmt/js/tests/unitary/express/routes/certificateRoutes.test.js
  iam/x509-identity-mgmt/js/tests/unitary/express/routes/internalCARoutes.test.js
  iam/x509-identity-mgmt/js/tests/unitary/express/routes/throwAwayRoutes.test.js
  iam/x509-identity-mgmt/js/tests/unitary/express/routes/trustedCARoutes.test.js
  iam/x509-identity-mgmt/js/tests/unitary/notifications/NotificationEngine.test.js
  iam/x509-identity-mgmt/js/tests/unitary/notifications/NotificationKafkaHealthCheck.test.js
  iam/x509-identity-mgmt/js/tests/unitary/notifications/OwnershipNotifier.test.js
  iam/x509-identity-mgmt/js/tests/unitary/notifications/TrustedCANofitier.test.js
  iam/x509-identity-mgmt/js/tests/unitary/services/CertificateService.test.js
  iam/x509-identity-mgmt/js/tests/unitary/services/TrustedCAService.test.js
  iam/x509-identity-mgmt/js/tests/util.test.js
Labels: Team:Security, Type:Feature

#2037 [x509-identity-mgmt] Internal endpoint to retrieve the trusted CAs bundle
  iam/x509-identity-mgmt/js/jest.config.js
  iam/x509-identity-mgmt/js/src/express/routes/certificateRoutes.js
  iam/x509-identity-mgmt/js/src/express/routes/sanitizeParams.js
  iam/x509-identity-mgmt/js/src/express/routes/throwAwayRoutes.js
  iam/x509-identity-mgmt/js/src/express/routes/trustedCARoutes.js
  iam/x509-identity-mgmt/js/src/services/TrustedCAService.js
  iam/x509-identity-mgmt/js/tests/unitary/express/routes/throwAwayRoutes.test.js
  iam/x509-identity-mgmt/js/tests/unitary/services/TrustedCAService.test.js
  iam/x509-identity-mgmt/js/tests/util.test.js
Labels: Team:Security, Type:Feature

#2040 [development] kafka ws fixes (gracefull shutdown and healthcheck improvements)
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Errors/ErrorCodes.js
  subscription-engine/kafka-ws/app/Kafka/KafkaConsumer.js
  subscription-engine/kafka-ws/app/Kafka/KafkaTopicsConsumerCallbacksMgmt.js
  subscription-engine/kafka-ws/app/Redis/RedisExpireMgmt.js
  subscription-engine/kafka-ws/app/Redis/RedisManager.js
  subscription-engine/kafka-ws/app/WebsocketTarball.js
  subscription-engine/kafka-ws/config/default.conf
  subscription-engine/kafka-ws/index.js
  subscription-engine/kafka-ws/package-lock.json
  subscription-engine/kafka-ws/package.json
  subscription-engine/kafka-ws/test/integration/AccessControl.test.js
  subscription-engine/kafka-ws/test/unit/KafkaConsumers.test.js
  subscription-engine/kafka-ws/test/unit/RedisManager.test.js
Labels: Team:Backend

#2044 Flag-enabled SubjectDN and DeviceExists validations
  iam/x509-identity-mgmt/README.md
  iam/x509-identity-mgmt/js/config/default.conf
  iam/x509-identity-mgmt/js/schemas/change-owner-certificate.json
  iam/x509-identity-mgmt/js/schemas/defs.json
  iam/x509-identity-mgmt/js/schemas/register-or-generate-certificate.json
  iam/x509-identity-mgmt/js/schemas/register-trusted-ca-certificate.json
  iam/x509-identity-mgmt/js/schemas/update-trusted-ca-certificate.json
  iam/x509-identity-mgmt/js/src/DIContainer.js
  iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrProvider.js
  iam/x509-identity-mgmt/js/src/services/CertificateService.js
  iam/x509-identity-mgmt/js/src/services/TrustedCAService.js
  iam/x509-identity-mgmt/js/tests/json-schema/certificates.test.js
  iam/x509-identity-mgmt/js/tests/json-schema/trustedCAs.test.js
  iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrProvider.test.js
  iam/x509-identity-mgmt/js/tests/unitary/services/CertificateService.test.js
Labels: Team:Backend, Team:Security, Type:Feature

#2050 [cert-sidecar] Obtaining the CA bundle file
  tools/cert-sidecar/README.md
  tools/cert-sidecar/app/App.js
  tools/cert-sidecar/app/CronsCertsMgmt.js
  tools/cert-sidecar/app/certificatesMgmt/Certificates.js
  tools/cert-sidecar/app/certificatesMgmt/index.js
  tools/cert-sidecar/app/x509IdentityMgmt/Requests.js
  tools/cert-sidecar/app/x509IdentityMgmt/index.js
  tools/cert-sidecar/config/default.conf
  tools/cert-sidecar/config/development.conf
  tools/cert-sidecar/package-lock.json
  tools/cert-sidecar/package.json
  tools/cert-sidecar/test/integration/CertificatesMgmt.test.js
  tools/cert-sidecar/test/integration/X509IdentityMgmt.test.js
  tools/cert-sidecar/test/unit/App.test.js
  tools/cert-sidecar/test/unit/CronsCertsMgmt.test.js
Labels: Team:Backend, Team:Security, Type:Feature

#2052 [x509-identity-mgmt] Support for content negotiation on internal endpoints
  iam/x509-identity-mgmt/js/src/express/routes/contentNegotiation.js
  iam/x509-identity-mgmt/js/src/express/routes/throwAwayRoutes.js
  iam/x509-identity-mgmt/js/tests/unitary/express/routes/throwAwayRoutes.test.js
Labels: Team:Backend, Team:Security, Type:Feature

#2055 [v0.6.0][kafka-ws] improved redis retry strategy
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Redis/RedisManager.js
  subscription-engine/kafka-ws/config/default.conf
  subscription-engine/kafka-ws/test/unit/RedisManager.test.js
Labels: Team:Backend

#2056 [dev][kafka-ws] improved redis retry strategy
  subscription-engine/kafka-ws/README.md
  subscription-engine/kafka-ws/app/Redis/RedisManager.js
  subscription-engine/kafka-ws/config/default.conf
  subscription-engine/kafka-ws/test/unit/RedisManager.test.js
Labels: Team:Backend

#2061 [cert-sidecar] documentation improvement
  tools/cert-sidecar/README.md
Labels: Type:Documentation
