Repository dojot/dojot, pull requests merged in 2021-02, with the labels that each got.

#1970 [development][fix] check x509-identity-mgmt readiness
  connector/mqtt/vernemq/broker/bin/vmq_dojot/vmq_dojot.sh
  connector/mqtt/vernemq/k2v-bridge/bin/scripts_tls/ejbca_client.sh
  connector/mqtt/vernemq/v2k-bridge/bin/scripts_tls/ejbca_client.sh
Labels: Type:Bug :bug:

#1968 fixed configManager json build
  subscription-engine/kafka-ws/index.js
Labels: Team:Backend

#1972 [v0.6.0] Fixed configManager json build
  subscription-engine/kafka-ws/index.js
Labels: Team:Backend

#1974 [v0.6.0] remove terminus
  subscription-engine/kafka-ws/app/Terminus.js
  subscription-engine/kafka-ws/config/default.conf
  subscription-engine/kafka-ws/index.js
  subscription-engine/kafka-ws/package-lock.json
  subscription-engine/kafka-ws/package.json
Labels: Team:Backend

#1984 [v0.6] fix healthcheck kafkaws v0.6
  subscription-engine/kafka-ws/Dockerfile
Labels: Team:Backend

#1985 [dev] fix healthcheck kafka-ws
  subscription-engine/kafka-ws/Dockerfile
Labels: Team:Backend

#1980 [x509-identity-mgmt] Device validation when associating with certificate
  iam/x509-identity-mgmt/README.md
  iam/x509-identity-mgmt/js/config/default.conf
  iam/x509-identity-mgmt/js/index.js
  iam/x509-identity-mgmt/js/package-lock.json
  iam/x509-identity-mgmt/js/package.json
  iam/x509-identity-mgmt/js/schemas/defs.json
  iam/x509-identity-mgmt/js/src/DIContainer.js
  iam/x509-identity-mgmt/js/src/core/tokenGen.js
  iam/x509-identity-mgmt/js/src/db/DeviceModel.js
  iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrEventEngine.js
  iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrEventRunnable.js
  iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrKafkaHealthCheck.js
  iam/x509-identity-mgmt/js/src/deviceManager/DeviceMgrProvider.js
  iam/x509-identity-mgmt/js/src/ejbca/EjbcaHealthCheck.js
  iam/x509-identity-mgmt/js/src/express/interceptors/readinessInterceptor.js
  iam/x509-identity-mgmt/js/src/services/CertificateService.js
  iam/x509-identity-mgmt/js/tests/json-schema/certificates.test.js
  iam/x509-identity-mgmt/js/tests/unitary/core/tokenGen.test.js
  iam/x509-identity-mgmt/js/tests/unitary/db/DeviceModel.test.js
  iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrEventEngine.test.js
  iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrEventRunnable.test.js
  iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrKafkaHealthCheck.test.js
  iam/x509-identity-mgmt/js/tests/unitary/deviceManager/DeviceMgrProvider.test.js
  iam/x509-identity-mgmt/js/tests/unitary/ejbca/EjbcaHealthCheck.test.js
  iam/x509-identity-mgmt/js/tests/unitary/services/CertificateService.test.js
Labels: Team:Security, Type:Feature
